type: one_to_one
engine_key: households_heating_solar_thermal_panels_share
display: slider
min: 0.0
max: 2.0
step: 1.0
start: 0.0
unit: number
formula: >
  number_of_households_heating_solar_thermal_collectors * 100.0 / 2.0