type: one_to_one
engine_key: households_useful_demand_electric_appliances
display: slider
min: -50
max: 100
step: 10.0
start: 0
unit: percentage
formula: >
  - 98.6 + 100.0 * (1.0 + number_of_appliances_in_the_house / 100.0) ** 0.05